import { CurriculumData } from '@/types';

export const NEXTJS_CURRICULUM: Record<string, CurriculumData> = {
    "nextjs": {
        id: "nextjs",
        fileName: "nextjs",
        description: "The AI Delivery Hub (Next.js Mastery)",
        category: "Next.js",
        subDescription: "Master Next.js for the AI Era. From the App Router and Server Actions to Vercel AI SDK, Generative UI, and Edge compute.",
        experienceLevels: ["1yoe", "2yoe", "3yoe", "4yoe", "4+yoe"],
        phases: [
            {
                phase: 1,
                title: "Setting up the Hub: Intro & Setup",
                targetExperience: ["1yoe"],
                theory: [
                    "Next.js vs React: The Delivery Network vs the Kitchen",
                    "Installation: Building the warehouse headquarters",
                    "Project Structure: Navigating the warehouse folders",
                    "The App Router: The modern GPS system"
                ],
                practicals: [
                    "Install a new Next.js 'Franchise'",
                    "Run the warehouse dev server and explore the App Router"
                ]
            },
            {
                phase: 2,
                title: "Mapping the Routes: Navigation",
                targetExperience: ["1yoe", "2yoe"],
                theory: [
                    "Folder-based Routing: Each folder is a delivery destination",
                    "Nested Routes: Branching out your delivery network",
                    "Dynamic Routes [id]: Handling unique 'Order IDs' in the URL",
                    "The <Link> Component: The fast-track delivery line"
                ],
                practicals: [
                    "Create routes for '/menu', '/orders', and '/profile'",
                    "Build a dynamic route for specific 'Dish IDs'"
                ]
            },
            {
                phase: 3,
                title: "Where to Cook? Server vs Client",
                targetExperience: ["2yoe"],
                theory: [
                    "Server Components: Pre-cooked at the warehouse (Secure & Fast)",
                    "Client Components: Cooking at the customer's table (Interactive)",
                    "The 'use client' Directive: Marking the table-side cooking zone",
                    "Composition Patterns: Passing server components as props to client components"
                ],
                practicals: [
                    "Build a fast 'Display Menu' (Server Component)",
                    "Build an interactive 'Review Button' (Client Component)"
                ]
            },
            {
                phase: 4,
                title: "The Direct Line: Server Actions",
                targetExperience: ["2yoe", "3yoe"],
                theory: [
                    "What are Server Actions? Sending orders directly to the chef",
                    "Form Handling: Securely capturing guest orders without API routes",
                    "Revalidating Paths: Updating the menu immediately after an order",
                    "Optimistic Updates: Displaying 'Order Received' before the server responds"
                ],
                practicals: [
                    "Build a 'Contact the Franchise' form using Server Actions",
                    "Implement an 'Instant Like' count that feels lightning fast"
                ]
            },
            {
                phase: 5,
                title: "Sourcing Ingredients & AI Streams",
                targetExperience: ["3yoe"],
                theory: [
                    "Async Server Components: Fetching ingredients directly in the warehouse",
                    "Streaming & Suspense: Delivering the UI shell while data/AI text streams in",
                    "Vercel AI SDK: The easiest way to stream text from LLMs",
                    "Data Validation: Checking ingredient quality (Zod)"
                ],
                practicals: [
                    "Use 'Suspense' to show a skeleton while a database query resolves",
                    "Implement `streamText` from the Vercel AI SDK to stream OpenAI responses"
                ]
            },
            {
                phase: 6,
                title: "Generative UI: AI beyond Text",
                targetExperience: ["3yoe", "4yoe"],
                theory: [
                    "Generative UI: Allowing LLMs to stream React components (Cards, Charts)",
                    "AI State vs UI State: Managing the brain vs what the user sees",
                    "Tool Calling in the Browser: Let the LLM trigger client-side actions",
                    "Interactive AI: Creating multi-turn conversational interfaces"
                ],
                practicals: [
                    "Use the Vercel AI SDK (`streamUI`) to render a Weather Component generated by an LLM",
                    "Build a chatbot that can render interactive charts based on user queries"
                ]
            },
            {
                phase: 7,
                title: "Grand Opening: Edge Compute & RAG",
                targetExperience: ["4yoe", "4+yoe"],
                theory: [
                    "The Edge Runtime: Running AI streams globally with zero cold starts",
                    "Vector Search in Next.js: Integrating with Vercel Postgres/pgvector",
                    "RAG at the Edge: Fetching embeddings before streaming the LLM response",
                    "Image Optimization & Caching: Keeping the warehouse efficient"
                ],
                practicals: [
                    "Deploy an Edge function that performs a fast Vector Similarity Search",
                    "Build a complete RAG-powered documentation chatbot in Next.js"
                ]
            }
        ]
    },
    "nextjs-questions": {
        id: "nextjs-questions",
        fileName: "nextjs-questions",
        description: "Next.js & AI Interview Warehouse",
        category: "Next.js",
        subDescription: "Master the 'Global Food Delivery' analogy and modern AI UI patterns for interviews.",
        experienceLevels: ["1yoe", "2yoe", "3yoe", "4yoe", "4+yoe"],
        phases: [
            {
                phase: 1,
                title: "Ground Floor: Fundamentals",
                targetExperience: ["1yoe", "2yoe"],
                theory: [
                    "Next.js vs Vanilla React (The Delivery Metaphor)",
                    "Server Components vs Client Components",
                    "What are Server Actions and why do they replace API routes?"
                ],
                practicals: [
                    "Explain ISR using a 'Freshness Timer' analogy",
                    "Compare SSG and SSR using 'Pre-packaged' vs 'Cook-to-order'"
                ]
            },
            {
                phase: 2,
                title: "Second Floor: AI & Advanced Logistics",
                targetExperience: ["3yoe", "4yoe", "4+yoe"],
                theory: [
                    "How does streaming work in the Vercel AI SDK?",
                    "What is Generative UI and how does it differ from text streaming?",
                    "How do you implement a RAG pipeline entirely within Next.js API routes/Server Actions?",
                    "Edge vs Node.js runtime for AI tasks"
                ],
                practicals: [
                    "Explain AI State vs UI State to a junior developer",
                    "Design a scalable architecture for an AI Chatbot using Next.js"
                ]
            }
        ]
    }
};

export const NESTJS_CURRICULUM: Record<string, CurriculumData> = {
    "nestjs": {
        id: "nestjs",
        fileName: "nestjs",
        description: "The AI Orchestrator (NestJS Mastery)",
        category: "NestJS",
        subDescription: "Welcome to the city government office. Master controllers, services, microservices, and AI Agent orchestration.",
        experienceLevels: ["1yoe", "2yoe", "3yoe", "4yoe", "4+yoe"],
        phases: [
            {
                phase: 1,
                title: "Building the Headquarters: Architecture",
                targetExperience: ["1yoe", "2yoe"],
                theory: [
                    "NestJS vs Express: The Master Blueprint vs the Carpenter's Tool-belt",
                    "Module Structure: Dividing the building into departments",
                    "The Decorator Pattern: Adding 'Department Labels' to your code",
                    "Controllers: The front-desk receptionists"
                ],
                practicals: [
                    "Install the NestJS CLI and create a new 'City Hall' building",
                    "Create a 'StaffController' with basic GET/POST endpoints"
                ]
            },
            {
                phase: 2,
                title: "The Specialists: Providers & Services",
                targetExperience: ["2yoe"],
                theory: [
                    "What is a Service? The back-office specialist who does the work",
                    "Dependency Injection (DI): Hiring a specialist automatically",
                    "Custom Providers: Injecting external AI Services (OpenAI API)",
                    "Guards & Pipes: Security bouncers and data inspectors"
                ],
                practicals: [
                    "Create an `OpenAiService` and inject it into your controllers",
                    "Build a pipe that validates if a user prompt is clean using class-validator"
                ]
            },
            {
                phase: 3,
                title: "The Record Room: DBs & Vector Search",
                targetExperience: ["3yoe"],
                theory: [
                    "TypeORM & Prisma: The digital filing cabinets",
                    "Entities & Repositories: Designing the folder structure",
                    "Vector Databases: Storing embeddings using pgvector in TypeORM",
                    "RAG Implementation: Querying the database for semantic similarity"
                ],
                practicals: [
                    "Connect your 'City Hall' to a PostgreSQL database with pgvector",
                    "Create an endpoint that accepts a query, searches vectors, and returns context"
                ]
            },
            {
                phase: 4,
                title: "Agentic Workflows: Queues & Events",
                targetExperience: ["4yoe"],
                theory: [
                    "BullMQ & Redis: Setting up a task queue for heavy AI workloads",
                    "Event Emitters: Decoupling long-running AI generation from the HTTP request",
                    "Agent Orchestration: Creating services that coordinate multiple LLM calls",
                    "Rate Limiting & Retries: Handling API failures gracefully"
                ],
                practicals: [
                    "Offload a 'Document Summarization' LLM task to a BullMQ queue",
                    "Emit a 'SummaryCompleted' event to notify the client via WebSockets"
                ]
            },
            {
                phase: 5,
                title: "Microservices & Distributed AI",
                targetExperience: ["4+yoe"],
                theory: [
                    "NestJS Microservices: Separating the AI brain from the API Gateway",
                    "Transports: gRPC and TCP for fast internal communication",
                    "Multi-Agent Systems: Deploying different specialized AI agents as microservices",
                    "Observability: Tracing requests across distributed AI systems"
                ],
                practicals: [
                    "Extract your `OpenAiService` into a standalone gRPC microservice",
                    "Implement distributed tracing to monitor how long the LLM takes to reply"
                ]
            }
        ]
    },
    "nestjs-questions": {
        id: "nestjs-questions",
        fileName: "nestjs-questions",
        description: "The Civil Service Exam (NestJS & AI)",
        category: "NestJS",
        subDescription: "Master the 'City Administration' vocabulary to prove you can manage complex AI systems.",
        experienceLevels: ["1yoe", "2yoe", "3yoe", "4yoe", "4+yoe"],
        phases: [
            {
                phase: 1,
                title: "Junior Administrator",
                targetExperience: ["1yoe", "2yoe"],
                theory: [
                    "Dependency Injection (The Phone System analogy)",
                    "Providers vs Controllers (Specialists vs Receptionists)",
                    "How do you inject a third-party SDK (like OpenAI) into a NestJS Module?"
                ],
                practicals: [
                    "Explain the lifecycle of a request using the 'Walking through the building' path"
                ]
            },
            {
                phase: 2,
                title: "Senior Mayor",
                targetExperience: ["3yoe", "4yoe", "4+yoe"],
                theory: [
                    "How do you handle long-running LLM tasks in NestJS without timing out the HTTP request?",
                    "Explain how you would orchestrate a multi-agent workflow using BullMQ and NestJS.",
                    "Microservices Transports: When to use Redis vs gRPC for AI services"
                ],
                practicals: [
                    "Design a scalable NestJS architecture for an AI Document Processing platform"
                ]
            }
        ]
    }
};

export const PYTHON_CURRICULUM: Record<string, CurriculumData> = {
    "python": {
        id: "python",
        fileName: "python",
        description: "The AI Pioneer (Python Mastery)",
        category: "Python",
        subDescription: "Welcome to the studio. From basic logic and FastAPI speed to RAG pipelines, LangChain, and Local LLMs.",
        experienceLevels: ["1yoe", "2yoe", "3yoe", "4yoe", "4+yoe"],
        phases: [
            {
                phase: 1,
                title: "Drafting the Script: Syntax & Logic",
                targetExperience: ["1yoe"],
                theory: [
                    "Python Syntax: The Writer's shorthand",
                    "Variables & Types: Casting your characters (Strings, Integers, Lists, Dicts)",
                    "Control Flow: Plot twists (if/else) and repetitive scenes (Loops)",
                    "Virtual Environments (venv/Conda): The Private Rehearsal Room"
                ],
                practicals: [
                    "Write a 'Hello Studio' script",
                    "Design a character sheet using Dictionaries and Lists"
                ]
            },
            {
                phase: 2,
                title: "Scene Rehearsals: Functions & OOP",
                targetExperience: ["1yoe", "2yoe"],
                theory: [
                    "Functions & Arguments (*args, **kwargs): Flexible scene rehearsals",
                    "Classes & Objects: Blueprints for complex character types",
                    "Error Handling: Dealing with 'Forgotten Lines' (Exceptions)",
                    "File I/O: Reading text data for basic AI processing"
                ],
                practicals: [
                    "Build a 'Scene Repeater' function with flexible arguments",
                    "Build an 'AIClient' class that securely loads an API key"
                ]
            },
            {
                phase: 3,
                title: "The Speed-Dubbing Booth: FastAPI & LLM APIs",
                targetExperience: ["2yoe", "3yoe"],
                theory: [
                    "FastAPI Fundamentals: The specialized, high-speed API booth",
                    "Pydantic: Ensuring strict character scripts (Data Validation & JSON schemas for LLMs)",
                    "Async/Await: Handling multiple LLM API calls at once",
                    "Calling OpenAI/Anthropic APIs from Python"
                ],
                practicals: [
                    "Build a lightning-fast 'Chat API' with FastAPI",
                    "Force an LLM to output valid JSON by validating it with a Pydantic model"
                ]
            },
            {
                phase: 4,
                title: "The Production Office: Django & SQL",
                targetExperience: ["3yoe"],
                theory: [
                    "Django vs FastAPI: The All-in-One Studio vs the specialized booth",
                    "Django ORM: Talking to the record room in plain English",
                    "Vector Extensions: Using pgvector with Python ORMs (SQLAlchemy / Django)",
                    "Storing embeddings in a relational database"
                ],
                practicals: [
                    "Start a new Django 'Studio' project",
                    "Create a model that stores a text document and its vector embedding"
                ]
            },
            {
                phase: 5,
                title: "AI Pipelines: LangChain & LlamaIndex",
                targetExperience: ["3yoe", "4yoe"],
                theory: [
                    "LangChain: The standardized toolkit for building AI apps",
                    "LlamaIndex: Connecting LLMs to your private data sources",
                    "Document Loaders & Text Splitters: Preparing data for the AI",
                    "Building a Retrieval-Augmented Generation (RAG) pipeline"
                ],
                practicals: [
                    "Use LangChain to build a simple Q&A chain over a text file",
                    "Use LlamaIndex to query a local PDF document"
                ]
            },
            {
                phase: 6,
                title: "Agentic Workflows & Multi-Agent Orchestration",
                targetExperience: ["4yoe"],
                theory: [
                    "Tool Calling: Giving the LLM the ability to run Python functions",
                    "LangGraph: Building cyclical, stateful agent workflows",
                    "Multi-Agent Orchestration (e.g., AutoGen, CrewAI): Agents talking to agents",
                    "Celery & Task Queues: Offloading heavy agent processing"
                ],
                practicals: [
                    "Build an agent that has a 'Calculator' tool and a 'Web Search' tool",
                    "Use LangGraph to build a persistent conversational agent",
                    "Offload a massive document processing task to a Celery worker"
                ]
            },
            {
                phase: 7,
                title: "The Film Archives: Local LLMs & Tensors",
                targetExperience: ["4+yoe"],
                theory: [
                    "Running Local Models: Using Ollama, llama.cpp, or vLLM",
                    "PyTorch Basics: Understanding the math behind the models (Tensors)",
                    "Fine-tuning (LoRA/QLoRA): Teaching the model a specific script",
                    "AI Security: Prompt Injection defense and evaluation"
                ],
                practicals: [
                    "Serve a local model (e.g., Llama 3) using vLLM and connect it to FastAPI",
                    "Write an evaluation script (LLM-as-a-judge) to score pipeline accuracy"
                ]
            }
        ]
    },
    "python-questions": {
        id: "python-questions",
        fileName: "python-questions",
        description: "The AI Script Review (Interview Prep)",
        category: "Python",
        subDescription: "Master Python questions for the modern AI engineering era.",
        experienceLevels: ["1yoe", "2yoe", "3yoe", "4yoe", "4+yoe"],
        phases: [
            {
                phase: 1,
                title: "Entry-Level Writer",
                targetExperience: ["1yoe", "2yoe"],
                theory: [
                    "Python Memory Management and the GIL",
                    "List vs Tuple vs Set vs Dictionary",
                    "How do you safely manage API keys using environment variables?",
                    "What is Pydantic and why is it useful for LLM structured outputs?"
                ],
                practicals: [
                    "Explain 'Decorators' using the 'Actor's Outfit' analogy",
                    "Compare FastAPI and Django for building an AI wrapper app"
                ]
            },
            {
                phase: 2,
                title: "Executive Producer",
                targetExperience: ["3yoe", "4yoe", "4+yoe"],
                theory: [
                    "Explain the architecture of a RAG system and the role of the Vector DB.",
                    "Asyncio vs Celery for handling long-running AI API calls",
                    "How does LangGraph differ from standard LangChain chains?",
                    "What are the challenges of serving open-weights models in production?"
                ],
                practicals: [
                    "Design a scalable API that processes PDFs and answers questions about them",
                    "Optimize a vector search query that is stalling the production"
                ]
            }
        ]
    }
};
