name: Foreman's Daily Log

on:
  schedule:
    - cron: "0 20 * * *" # Every night
  workflow_dispatch:

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Daily Commits
        id: commits
        run: |
          COMMITS=$(git log --since="24 hours ago" --pretty=format:"%s")
          echo "msgs<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Update Log
        env:
          COMMIT_MESSAGES: ${{ steps.commits.outputs.msgs }}
        run: node scripts/foreman.mjs
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "docs: sync foreman's daily log" || exit 0
          git pull --rebase origin main --autostash
          git push
